import * as printer from ".."
import * as test from "blue-tape"

test("test exports", async test => {
  test.equal(typeof printer, "object")
  test.equal(typeof printer.concat, "function")
  test.equal(typeof printer.join, "function")
  test.equal(typeof printer.line, "object")
  test.equal(typeof printer.softline, "object")
  test.equal(typeof printer.hardline, "object")
  test.equal(typeof printer.literalline, "object")
  test.equal(typeof printer.group, "function")
  test.equal(typeof printer.conditionalGroup, "function")
  test.equal(typeof printer.fill, "function")
  test.equal(typeof printer.lineSuffix, "function")
  test.equal(typeof printer.lineSuffixBoundary, "object")
  test.equal(typeof printer.cursor, "object")
  test.equal(typeof printer.breakParent, "object")
  test.equal(typeof printer.ifBreak, "function")
  test.equal(typeof printer.indent, "function")
  test.equal(typeof printer.align, "function")
  test.equal(typeof printer.addAlignmentToDoc, "function")
  test.equal(typeof printer.printDocToString, "function")
  test.equal(typeof printer.isEmpty, "function")
  test.equal(typeof printer.willBreak, "function")
  test.equal(typeof printer.isLineNext, "function")
  test.equal(typeof printer.traverseDoc, "function")
  test.equal(typeof printer.mapDoc, "function")
  test.equal(typeof printer.propagateBreaks, "function")
  test.equal(typeof printer.printDocToDebug, "function")
})
